# Generated by Django 3.1.6 on 2021-02-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0002_auto_20210209_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
