# Generated by Django 3.1.6 on 2021-02-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0003_auto_20210209_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=255),
        ),
    ]
