# Generated by Django 3.1.6 on 2021-02-09 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0004_auto_20210209_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_no', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('martial_status', models.CharField(choices=[('married', 'Married'), ('single', 'Single'), ('divorsed', 'Divorsed'), ('widow', 'Widow'), ('widower', 'Widower')], max_length=255)),
                ('next_of_kin_phone_number', models.CharField(max_length=255)),
                ('next_of_kin_name', models.CharField(max_length=255)),
                ('next_of_kin_relationship', models.CharField(choices=[('father', 'Father'), ('son', 'Son'), ('wife', 'Wife'), ('husband', 'Husband'), ('mother', 'Mother'), ('sister', 'Sister'), ('brother', 'Brother'), ('relative', 'Relative'), ('friend', 'Friend')], max_length=255)),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('unemployed', 'UnEmployed')], max_length=255)),
                ('policy_id', models.CharField(max_length=255)),
                ('has_subscribed', models.BooleanField(default=False)),
                ('enrollment_address', models.CharField(max_length=255)),
                ('enrollment_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
