# Generated by Django 3.1.6 on 2021-02-10 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0005_enrollee'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollee',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollee',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollee',
            name='registeration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
