# Generated by Django 3.1.6 on 2021-02-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0007_auto_20210210_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollee',
            name='latitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enrollee',
            name='longitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
