# Generated by Django 3.1.6 on 2021-02-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0009_auto_20210210_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollee',
            name='latitude',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollee',
            name='longitude',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
