# Generated by Django 3.1.6 on 2021-02-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0010_auto_20210210_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollee',
            name='group_size',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='enrollee',
            name='group_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], default='individual', max_length=255),
            preserve_default=False,
        ),
    ]
