# Generated by Django 3.1.6 on 2021-02-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0011_auto_20210222_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollee',
            name='date_of_birth',
        ),
    ]
